### ISSUE TITLE
Примеры ThreadPool

### ISSUE THREAD

**Issue by mat0thew** [qoollo/dotNet-turbo#1]
Привет!

У вас есть еще пример использования ThreadPool?

**Comment by ikopylov** [comment]
А какие конкретно примеры интересуют?
В wiki есть простейший пример использования: https://github.com/qoollo/dotNet-turbo/wiki/Thread-Pool

**Comment by mat0thew** [comment]
@ikopylov я его разабрал, спасибо. К примеру запись в один файл с нескольких потоков.

**Comment by ikopylov** [comment]
> К примеру запись в один файл с нескольких потоков.

Не очень понятно, зачем в данной задаче нужен пул потоков. Единый файл будет точкой синхронизации между потоками и, скорее всего, поглотит всю выгоду от параллелизма. 

Пул потоков лучше всего подходит для параллелизации разнородных неблокирующихся задач. Если есть какой-то процент блокирующихся задач, то можно использовать динамчиеский пул. Он будет выделять новые потоки, чтобы загрузить CPU по максимуму вычислительными задачами.

В приведённом же примере все задачи будут блокироваться на общем ресурсе - файле. В итоге выигрыша никакого не будет.

**Comment by mat0thew** [comment]
Понемногу разбираюсь. Спасибо за библиотеку!
