### ISSUE TITLE
BalancingDynamicPoolManager: Exception

### ISSUE THREAD

**Issue by nmenshov** [qoollo/dotNet-turbo#4]
Message: System.MissingMethodException: Method not found: 'Qoollo.Turbo.ObjectPools.RentedElementMonitor`1<System.__Canon> Qoollo.Turbo.ObjectPools.ObjectPoolManager`1.Rent(Int32, System.String, System.String, Int32)'.

**Comment by ikopylov** [comment]
This method is from the debug version of library. After swithing to the release version you should rebuild all dependent projects.
