### ISSUE TITLE
English comments

### ISSUE THREAD

**Issue by micdenny** [qoollo/dotNet-turbo#6]
In the latest pre-release version `2.3.0-alpha` I see comments in what I suppose is a Cyrillic language, then I see that in the repo probably you already did all the translation, is it possible at least to have a pre-release package?

![image](https://user-images.githubusercontent.com/1633595/36608634-ab801b00-18ca-11e8-9afe-29ac2414e62e.png)

**Comment by ikopylov** [comment]
The next version with .NET Core support will be released in the next couple of weeks. All comments on the public surface will be translated to English in that release.

**Comment by micdenny** [comment]
Great!! Would be great to translate also the private surface, to be opened for contribution

**Comment by ikopylov** [comment]
> Would be great to translate also the private surface, to be opened for contribution

I agree. I will try to do that too, if I find the time.

**Comment by micdenny** [comment]
GReat thank you!!

**Comment by ikopylov** [comment]
I have released a new version of the library. 
All comments on the public surface and many comments on the private surfrace are translated to English. There are still a number of internal classes with untranslated comments, but I have no time to process them. 
I think that the most important things are covered, so I'm going to close this issue.
